/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.108
 * Generated at: 2021-05-05 08:54:36 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Change_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

String str_male;
	String str_female;
  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>变更学生信息</title>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tfunction modification() {\r\n");
      out.write("\t\tdocument.getElementById(\"change_table\").submit();\r\n");
      out.write("\t\treturn true;\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction clean() {\r\n");
      out.write("\t\tdocument.getElementById('name_1').value = \"\";\r\n");
      out.write("\t\tdocument.getElementById('age_1').value = \"\";\r\n");
      out.write("\t\tdocument.getElementById('native_2').value = \"\";\r\n");
      out.write("\t\tdocument.getElementById('dept_1').value = \"\";\r\n");
      out.write("\t\tdocument.getElementById('sex_1').checked=false;\r\n");
      out.write("\t\tdocument.getElementById('sex_2').checked=false;\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t");
      out.write('\r');
      out.write('\n');
      out.write('	');
      out.write("\r\n");
      out.write("\t<div align=\"center\">\r\n");
      out.write("\t\t<font size=\"5\">修改纪录</font>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t");
      out.write('\r');
      out.write('\n');
      out.write('	');

		request.setCharacterEncoding("utf-8");
		if (request.getParameter("sex").equals("男")) {
			str_male = "checked";
			str_female = "";
		} else {
			str_male = "";
			str_female = "checked";
		}
	
      out.write("\r\n");
      out.write("\t<form action=\"Change_Query.jsp\" method=\"post\" id=\"change_table\">\r\n");
      out.write("\t\t<table width=\"30%\" border=\"1\" align=\"center\">\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th>学号</th>\r\n");
      out.write("\t\t\t\t<!-- 设置该字段为只读 -->\r\n");
      out.write("\t\t\t\t<td align=\"center\"><input name=\"id\" type=\"text\" readonly=\"readonly\" value='");
      out.print(request.getParameter("id"));
      out.write("' id=\"id_1\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th>姓名</th>\r\n");
      out.write("\t\t\t\t<td align=\"center\"><input type=\"text\" name=\"name\" value='");
      out.print(request.getParameter("name"));
      out.write("' id=\"name_1\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th>性别</th>\r\n");
      out.write("\t\t\t\t<!-- 此处动态选择单选框 -->\r\n");
      out.write("\t\t\t\t<td align=\"center\">\r\n");
      out.write("\t\t\t\t男<input type=\"radio\" name=\"sex\" id=\"sex_1\" value=\"男\" ");
      out.print(str_male);
      out.write(">&nbsp;&nbsp; \r\n");
      out.write("\t\t\t\t\t女<input type=\"radio\" name=\"sex\" id=\"sex_2\" value=\"女\" ");
      out.print(str_female);
      out.write(">\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th>年龄</th>\r\n");
      out.write("\t\t\t\t<td align=\"center\"><input type=\"text\" name=\"age\" value='");
      out.print(request.getParameter("age"));
      out.write("' id=\"age_1\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th>籍贯</th>\r\n");
      out.write("\t\t\t\t<td align=\"center\"><input type=\"text\" name=\"native_1\" value='");
      out.print(request.getParameter("native_1"));
      out.write("' id=\"native_2\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th>院系</th>\r\n");
      out.write("\t\t\t\t<td align=\"center\"><input type=\"text\" name=\"dept\" value='");
      out.print(request.getParameter("dept"));
      out.write("' id=\"dept_1\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<!-- 此处需要合并单元格 -->\r\n");
      out.write("\t\t\t\t<td align=\"center\" colspan=\"2\"><input type=\"button\" value=\"提交\" onclick=\"modification()\">&nbsp; <input type=\"button\" value=\"清空\" onclick=\"clean()\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</form>\r\n");
      out.write("\t<div align=\"center\">\r\n");
      out.write("\t\t<a href=\"List.jsp\">返回</a>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
